### ISSUE TITLE
Check if user already exists before registering

### ISSUE THREAD

**Issue by LirSegev** [LirSegev/LifeLogger#9]

**Comment by NadhirB** [comment]
Finished, couldn't close through sublime merge/

**Comment by LirSegev** [comment]
@NadhirB you need to write "Close #9" in the pull request. Either in the description or in the commit message at the end. It will get closed only after the branch is merged.

**Comment by LirSegev** [comment]
@NadhirB You can reference issues in normal commits like this: "#9", but you can only close them with pull request/merge to master.
